export default {
    products: [
      {
        _id: '1',
        name: 'Harry Potter Collection',
        category: 'Entertainment',
        image: '/images/harryportar.jpg',
        price: 60,
        brand: ' Spiral-bound',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'Battle Ground',
        category: 'Entertainment',
        image: '/images/battle.jpg',
        price: 50,
        brand: ' Audible-Audiobook',
        rating: 4.2,
        numReviews: 5
      },
      {
        _id: '3',
        name: 'Battle Grounds',
        category: 'History',
        image: '/images/battleground.jpg',
        price: 70,
        brand: ' Hard Cover',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      }, {
        _id: '4',
        name: 'Dog Man:Grime and Punishment',
        category: 'History',
        image: '/images/dogman.jpg',
        price: 70,
        brand: ' Hard Cover',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      },
      {
        _id: '5',
        name: 'The Princess And The Fan Girl',
        category: 'History',
        image: '/images/princess.jpg',
        price: 70,
        brand: ' Hard Cover',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'One Vote Away',
        category: 'Entertainment',
        image: '/images/onevote.jpg',
        price: 70,
        brand: ' Hard Cover',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      },
      {
        _id: '7',
        name: 'Leave The World Behind',
        category: 'History',
        image: '/images/leave.jpg',
        price: 70,
        brand: ' Spiral-bound',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      },
      {
        _id: '8',
        name: 'John Grisham',
        category: 'Entertainment',
        image: '/images/john.jpg',
        price: 70,
        brand: ' Hard Cover',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      },
    ]
  }